server:
  port: 9296

spring:
  application:
    name: UMS-CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/IKCONDev/ums-config-server
          clone-on-start: true
